### ISSUE TITLE
[Feature]: 关于反馈栏

### ISSUE THREAD

**Issue by ynjq** [XtremeWave/TownOfNewEpic_XtremeSite#12]
### 联系方式(邮箱)

diedmom@outlook.com

### 新功能的详细描述是什么?

我们完全可以增加一个投稿/反馈区或者干脆把邮箱或联系方式扔那，给对职业/故事/网站有想法的人一个提供想法/投稿的地方，又或是放出我们现在面临的问题等待热心群众的答复。实际上如果投稿够多的话我们甚至连后续版本搞什么都知道了。虽然这可能对开发组那边上点压力就是了（雾隐）。

### 此功能的实现思路是什么?

提供联系邮箱（我的也可以）或是开创一个新的分区，如果可以的话设置一个匿名选项是极好的。

**Comment by QingFeng-awa** [comment]
> 我们完全可以增加一个投稿/反馈区或者干脆把邮箱或联系方式扔那，给对职业/故事/网站有想法的人一个提供想法/投稿的地方，又或是放出我们现在面临的问题等待热心群众的答复。

那你现在应该在网站里看到反馈页面而不是**在GitHub提issue**。
